### ISSUE TITLE
리뷰 별점

### ISSUE THREAD

**Issue by ashleysyheo** [woowacourse-teams/2023-zipgo#177]
### 🐞 Describe

<img width="663" alt="Screenshot 2023-08-07 at 1 38 52 PM" src="https://github.com/woowacourse-teams/2023-zipgo/assets/51967731/634755d8-20d8-447d-abf1-6c4456299b29">

이 페이지에서 뒤로가기 버튼을 클릭하면 별점이 0으로 초기화 되어 있음. 

### 🌏 Environment

모든 곳

**Comment by HyeryongChoi** [comment]
#482 사용자 피드백 반영 완료~~
