### ISSUE TITLE
[버그아님] 별점 수정이 가능했으면 좋겠음, 이상반응 여러개 선택할 수 있다는 거 알 수 있었으면 좋겠음

### ISSUE THREAD

**Issue by Dahyeeee** [woowacourse-teams/2023-zipgo#182]
### 🐞 Describe

별점 수정이 가능했으면 좋겠어요 실수로 누르고 리뷰 작성하다가 수정하려고 뒤로 가기 했는데 작성한 내역이 사라져 있어서 불편해요! 

대변상태랑 기호성은 하나밖에 선택못하는데 이상반응은 여러개 선택가능하니까 여러개 선택 가능하다는 문구가 있다면 유용할 것 같아요! 

### 🌏 Environment

버그 아님

**Comment by kyY00n** [comment]
이 이슈는 피처로 변경해두겠습니다 :D 제보 감사합니다!
