### ISSUE TITLE
필터 적용 후 다시 필터 눌렀을 때 이전 값이 보였으면 좋겠어요

### ISSUE THREAD

**Issue by kdkdhoho** [woowacourse-teams/2023-zipgo#184]
### 🐞 Describe

버그는 아니지만 필터 적용 후 다시 필터 눌렀을 때 일부 값을 수정하려고 했는데 이전 값이 모두 사라져서 불편해요!

### 🌏 Environment

OS: Ventura 13.4.1

**Comment by iamjooon2** [comment]
이 이슈는 피처로 변경해두겠습니다 :D 제보 감사합니다!
