### ISSUE TITLE
별점 소수점

### ISSUE THREAD

**Issue by ashleysyheo** [woowacourse-teams/2023-zipgo#186]
### 🐞 Describe

<img width="664" alt="Screenshot 2023-08-07 at 1 58 42 PM" src="https://github.com/woowacourse-teams/2023-zipgo/assets/51967731/b7f1d8a6-d61c-4b2d-a9e7-e7da251b6ab2">
3.3333333333333335까지 보여줄 필요가 있을까요???

### 🌏 Environment

모든 곳

**Comment by kyY00n** [comment]
#201 에서 처리했습니다!
