### ISSUE TITLE
아이폰에서 카카오 로그인하면 ssl 에러 떠요!

### ISSUE THREAD

**Issue by kdkdhoho** [woowacourse-teams/2023-zipgo#189]
### 🐞 Describe

브라우저에서는 이상없었는데 아이폰에서 로그인하면 이 화면이 떠요!

![IMG_EC3DD9B0B129-1](https://github.com/woowacourse-teams/2023-zipgo/assets/66300965/5eb41c00-246f-49c4-b3c8-8d7fe960348f)

### 🌏 Environment

iOS 16.5.1(c)

**Comment by kdkdhoho** [comment]
다시 로그인 누르니까 또 제대로 되네요..?

**Comment by HyeryongChoi** [comment]
@kdkdhoho 브라우저는 뭘로 하셨나요~?

**Comment by kdkdhoho** [comment]
@HyeryongChoi 웨일로 했습니다~
