### ISSUE TITLE
리뷰 작성 후 완료 버튼 누른 뒤 새로고침하는 화면을 두 번 반복하면 예외가 발생

### ISSUE THREAD

**Issue by shin-mallang** [woowacourse-teams/2023-zipgo#190]
### 🐞 Describe

리뷰 작성 -> 리뷰 작성이 완료되었습니다(알림창) 에서 새로고침 ->
리뷰 작성 -> 리뷰 작성이 완료되었습니다(알림창) 에서 새로고침 -> 예외 발생

![image](https://github.com/woowacourse-teams/2023-zipgo/assets/52229930/a8528a43-17ae-46e4-84b9-82c4afe9cad6)
![image](https://github.com/woowacourse-teams/2023-zipgo/assets/52229930/eb7fa3db-2a07-4be9-818f-bc6d3d1cecc4)
![image](https://github.com/woowacourse-teams/2023-zipgo/assets/52229930/23fbf9cd-98e0-43df-be3e-8bf8481958c2)

### 🌏 Environment

아이폰 사파리

**Comment by wonyongChoi05** [comment]
말랑 대체 이런 예외는 어떻게 찾는거임

**Comment by shin-mallang** [comment]
버그마스터 ㅋㅋ
