### ISSUE TITLE
나이로도 필터링했으면 좋겠어요

### ISSUE THREAD

**Issue by kdkdhoho** [woowacourse-teams/2023-zipgo#191]
### 🐞 Describe

퓨리나 사료 중에 나이의 기준이 많이 있던데 나이로도 필터링했으면 좋겠어요

### 🌏 Environment

MacBook Air Ventura 13.4.1(c)

**Comment by kyY00n** [comment]
이 이슈는 피처로 변경해두겠습니다 :D 제보 감사합니다!
