### ISSUE TITLE
리뷰가 최근에 남긴 순으로 떴으면 좋겠어요

### ISSUE THREAD

**Issue by dladncks1217** [woowacourse-teams/2023-zipgo#196]
### 🐞 Describe

<img width="593" alt="스크린샷 2023-08-07 오후 2 12 54" src="https://github.com/woowacourse-teams/2023-zipgo/assets/45068522/4c8ef39d-faf0-4320-a0f5-7a6f53397660">

지금은 예전에 작성했던게 위에 뜹니다.

### 🌏 Environment

1

**Comment by kyY00n** [comment]
이 이슈는 피처로 변경해두겠습니다 :D 제보 감사합니다!

**Comment by iamjooon2** [comment]
반영 완료하였습니다! 감사합니다 :D
