### ISSUE TITLE
[실종] 무무

### ISSUE THREAD

**Issue by wonyongChoi05** [woowacourse-teams/2023-zipgo#294]
## 민무 없는 집고팀 상황
![image](https://github.com/woowacourse-teams/2023-zipgo/assets/94087228/9e17bde4-2b15-422d-99c5-884cbcdd272a)

### ✅ Tasks

흑흑

**Comment by ksone02** [comment]
이건 좀 심각하네요...

**Comment by iamjooon2** [comment]
당사자 발견으로 해당 이슈 닫아두겠습니다. 제보 감사합니다 :D
