### ISSUE TITLE
1차 데모 랜딩 페이지 구현

### ISSUE THREAD

**Issue by n0eyes** [woowacourse-teams/2023-zipgo#39]
### ✨ Describe

앱 전역에 적용되는 최상위 레이아웃을 설정한다

### ✅ Tasks

- [x] 전역 레이아웃 설정
- [x] Header, Footer 추가
- [x] ToggleBox 추가
- [x] FoodList 추가

**Comment by wonyongChoi05** [comment]
노아야 자라....
